ERROR - 2025-09-11 01:45:16 --> mysqli_sql_exception: Table 'san_miguel_hms_new.prescriptions' doesn't exist in engine in C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\hms_group4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\hms_group4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\hms_group4\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\hms_group4\app\Models\PrescriptionModel.php(41): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\hms_group4\app\Controllers\Doctor.php(200): App\Models\PrescriptionModel->getByDoctor('yad')
#8 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(933): App\Controllers\Doctor->prescriptions()
#9 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Doctor))
#10 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\hms_group4\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\hms_group4\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\hms_group4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-09-11 01:45:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'san_miguel_hms_new.prescriptions' doesn't exist in engine
[Method: GET, Route: doctor/prescriptions]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = :doctor_name:
ORDER BY `created_date` DESC', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\PrescriptionModel.php(41): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\Doctor.php(200): App\Models\PrescriptionModel->getByDoctor('yad')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Doctor->prescriptions()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Doctor))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 01:45:16 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'san_miguel_hms_new.prescriptions' doesn't exist in engine
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = \'yad\'
ORDER BY `created_date` DESC')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = \'yad\'
ORDER BY `created_date` DESC')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = :doctor_name:
ORDER BY `created_date` DESC', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\PrescriptionModel.php(41): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\Doctor.php(200): App\Models\PrescriptionModel->getByDoctor('yad')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Doctor->prescriptions()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Doctor))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 01:45:16 --> [Caused by] mysqli_sql_exception: Table 'san_miguel_hms_new.prescriptions' doesn't exist in engine
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = \'yad\'
ORDER BY `created_date` DESC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = \'yad\'
ORDER BY `created_date` DESC')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = \'yad\'
ORDER BY `created_date` DESC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = :doctor_name:
ORDER BY `created_date` DESC', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\PrescriptionModel.php(41): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\Doctor.php(200): App\Models\PrescriptionModel->getByDoctor('yad')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Doctor->prescriptions()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Doctor))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-09-11 01:45:32 --> mysqli_sql_exception: Table 'san_miguel_hms_new.prescriptions' doesn't exist in engine in C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\hms_group4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\hms_group4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\hms_group4\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\hms_group4\app\Models\PrescriptionModel.php(41): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\hms_group4\app\Controllers\Doctor.php(200): App\Models\PrescriptionModel->getByDoctor('yad')
#8 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(933): App\Controllers\Doctor->prescriptions()
#9 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Doctor))
#10 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\hms_group4\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\hms_group4\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\hms_group4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-09-11 01:45:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'san_miguel_hms_new.prescriptions' doesn't exist in engine
[Method: GET, Route: doctor/prescriptions]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = :doctor_name:
ORDER BY `created_date` DESC', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\PrescriptionModel.php(41): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\Doctor.php(200): App\Models\PrescriptionModel->getByDoctor('yad')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Doctor->prescriptions()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Doctor))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 01:45:32 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'san_miguel_hms_new.prescriptions' doesn't exist in engine
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = \'yad\'
ORDER BY `created_date` DESC')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = \'yad\'
ORDER BY `created_date` DESC')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = :doctor_name:
ORDER BY `created_date` DESC', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\PrescriptionModel.php(41): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\Doctor.php(200): App\Models\PrescriptionModel->getByDoctor('yad')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Doctor->prescriptions()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Doctor))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 01:45:32 --> [Caused by] mysqli_sql_exception: Table 'san_miguel_hms_new.prescriptions' doesn't exist in engine
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = \'yad\'
ORDER BY `created_date` DESC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = \'yad\'
ORDER BY `created_date` DESC')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = \'yad\'
ORDER BY `created_date` DESC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `prescriptions`
WHERE `doctor_name` = :doctor_name:
ORDER BY `created_date` DESC', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\PrescriptionModel.php(41): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\Doctor.php(200): App\Models\PrescriptionModel->getByDoctor('yad')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Doctor->prescriptions()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Doctor))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 15:17:31 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_inventory.php"
[Method: GET, Route: laboratory/inventory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_inventory.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_inventory', [], true)
 3 APPPATH\Controllers\Laboratory.php(90): view('auth/laboratory_inventory')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->inventory()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 15:17:35 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_inventory.php"
[Method: GET, Route: laboratory/inventory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_inventory.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_inventory', [], true)
 3 APPPATH\Controllers\Laboratory.php(90): view('auth/laboratory_inventory')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->inventory()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 16:59:37 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 16:59:43 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:02:27 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:03:26 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:03:29 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:06:41 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:09:13 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:09:18 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:10:54 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:10:54 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:10:58 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:10:59 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:14:42 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:14:45 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:14:46 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:14:47 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:17:31 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:18:13 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:18:14 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:18:40 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:20:00 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:20:02 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:20:15 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:22:36 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:22:37 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-11 17:23:49 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/laboratory_dashboard.php"
[Method: GET, Route: laboratory]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/laboratory_dashboard.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/laboratory_dashboard', [], true)
 3 APPPATH\Controllers\Laboratory.php(12): view('auth/laboratory_dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Laboratory->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Laboratory))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
